import assert from 'node:assert/strict';
import { readFileSync } from 'node:fs';

const index = readFileSync(new URL('../index.html', import.meta.url), 'utf8');
const bootstrap = readFileSync(new URL('../src/safe-ui-bootstrap.js', import.meta.url), 'utf8');
const controller = readFileSync(new URL('../src/static-browser-diagnostics-controller.js', import.meta.url), 'utf8');
const checklist = readFileSync(new URL('../docs/post-pr133-recovery-checklist.md', import.meta.url), 'utf8');
const pkg = JSON.parse(readFileSync(new URL('../package.json', import.meta.url), 'utf8'));

const activeCacheKey = 'support-ui-render-export-fix-20260623';
const phaseKeyPattern = /input-always-visible-20260619|phase4-global-esc-lifecycle-20260619|phase4a-static-input-panel-cleanup-20260619|perf-static-shell-20260620|perf-lcp-deferred-app-20260620|perf-idle-diagnostics-20260620|perf-tdz-fix-20260620|canvas-tool-manager-20260620|tool-fixes-v2-20260620/;
const onReadyBody = controller.match(/function onReady\(\) \{([\s\S]*?)\n\}/)?.[1] || '';

assert.match(index, new RegExp(activeCacheKey));
assert.doesNotMatch(index, /fresh-clip-core-20260619/);
assert.match(index, new RegExp(`safe-ui-bootstrap\\.js\\?v=${activeCacheKey}`));
assert.match(bootstrap, phaseKeyPattern);
assert.match(bootstrap, /LATE_IDLE_MODULE_URLS[\s\S]*static-browser-diagnostics-controller\.js\?v=\$\{SAFE_UI_VERSION\}/);
assert.doesNotMatch(bootstrap, /static-properties-actions-controller\.js/);
assert.match(bootstrap, /emitBootstrapModuleFailure\(/);
assert.match(bootstrap, /CustomEvent\('viewer:static-shell-module-failed'/);
assert.match(controller, /BROWSER_DIAGNOSTICS_VERSION = 'tool-fixes-v2-20260620'/);
assert.match(controller, /EXPECTED_SHELL_VERSION = 'tool-fixes-v2-20260620'/);
assert.match(controller, /STALE_SHELL_VERSION = 'perf-static-drawer-bundle-20260620'/);
assert.match(controller, /detectStaleShellAssets/);
assert.match(controller, /collectWebglInfo/);
assert.match(controller, /scheduleHeavyDiagnosticsProbes/);
assert.match(controller, /runHeavyDiagnosticsProbes/);
assert.doesNotMatch(onReadyBody, /collectWebglInfo\(/);
assert.match(controller, /sampleFrameTime/);
assert.match(controller, /installWheelLatencyProbe/);
assert.match(controller, /requestAnimationFrame/);
assert.match(controller, /requestIdleCallback/);
assert.match(controller, /isChrome/);
assert.match(controller, /isEdge/);
assert.match(controller, /recordModuleFailure/);
assert.match(controller, /Chrome cache\/module issue detected/);
assert.match(controller, /Chrome frame-time lag detected/);
assert.match(controller, /shouldShowJankWarning\(sample, longTasks\)/);
assert.match(controller, /sample\.visibilityState === 'visible'/);
assert.match(controller, /sample\.hadFocus === true/);
assert.match(controller, /longTasks\.supported === true[\s\S]*longTasks\.totalMs >= JANK_LONG_TASK_MS_THRESHOLD/);
assert.doesNotMatch(controller, /type:\s*['"]wheel-latency['"][\s\S]{0,240}recordRuntimeWarning/);
assert.match(controller, /Ctrl\+F5/);
assert.match(controller, /Disable cache/);
assert.match(controller, /clear site data/i);
assert.match(controller, /__3D_MARKUP_BROWSER_DIAGNOSTICS__/);
assert.match(controller, /noIntervalPolling: true/);
assert.match(controller, /frameTimeProbe: true/);
assert.match(controller, /wheelLatencyProbe: true/);
assert.match(controller, /staleShellProbe: true/);
assert.match(controller, /deferredWebglProbe: true/);
assert.match(controller, /jankWarningRequiresLongTasks: true/);
assert.doesNotMatch(controller, /setInterval\(/);
assert.match(checklist, /X1 — Chrome-only erratic response/);
assert.match(checklist, /X2 — Chrome runtime\/cache diagnostics/);
assert.match(pkg.scripts.test, /browser-diagnostics\.test\.mjs/);

console.log('browser diagnostics gate passed');
