import assert from 'node:assert/strict';
import { readFileSync } from 'node:fs';

const index = readFileSync(new URL('../index.html', import.meta.url), 'utf8');
const bootstrap = readFileSync(new URL('../src/safe-ui-bootstrap.js', import.meta.url), 'utf8');
const appLoader = readFileSync(new URL('../src/app-loader.js', import.meta.url), 'utf8');
const controller = readFileSync(new URL('../src/static-input-always-visible-controller.js', import.meta.url), 'utf8');
const managedJsonUi = readFileSync(new URL('../src/managed-stage-json-ui-controller.js', import.meta.url), 'utf8');
const perfCss = readFileSync(new URL('../src/static-shell-performance.css', import.meta.url), 'utf8');
const checklist = readFileSync(new URL('../docs/post-pr133-recovery-checklist.md', import.meta.url), 'utf8');
const pkg = JSON.parse(readFileSync(new URL('../package.json', import.meta.url), 'utf8'));

const activeKey = 'input-persistent-root-card-20260626';
const staticKeyPattern = /input-persistent-root-card-20260626|input-root-owner-20260626|input-postbootstrap-reassert-20260626|input-load-controls-restored-20260626|workflow-input-expanded-load-controls-20260625|staged-json-review-ui-rvm-fix-20260625|app-boot-dialog-conversion-hotfix-20260623|support-ui-render-export-fix-20260623|tool-fixes-v2-20260620|perf-tdz-fix-20260620|perf-static-drawer-bundle-20260620|perf-idle-diagnostics-20260620|perf-static-shell-20260620|phase4a-static-input-panel-cleanup-20260619/;

assert.match(index, /id="inputFileStatus"[\s\S]*No file chosen/);
assert.match(index, /id="inputStatus"/);
assert.match(index, /<span>Choose stagedJson<\/span>/);
assert.match(index, /id="loadUnifiedModelFileBtn"[\s\S]*Import stagedJson/);
assert.match(index, /id="loadSampleBtn"[\s\S]*Load BM_CII stagedJson/);
assert.match(index, /id="clearBtn"[\s\S]*Clear All/);
assert.match(index, /data-owner="source-html"/);
assert.match(index, /class="panel-section input-root-card/);
assert.match(index, /data-input-root="persistent"/);
assert.doesNotMatch(index, /class="panel-section workflow-card[^"]*"[^>]*data-section="input"/);
assert.match(index, new RegExp(activeKey));
assert.match(index, staticKeyPattern);
assert.doesNotMatch(index, /core-safe-boot-20260619|Choose InputXML|Load InputXML|from InputXML/);

assert.match(bootstrap, new RegExp(activeKey));
assert.match(bootstrap, /static-input-always-visible-controller\.js\?v=\$\{SAFE_UI_VERSION\}/);
assert.doesNotMatch(bootstrap, /early static shell source parity/);
assert.match(bootstrap, new RegExp(`SAFE_UI_VERSION = '(${staticKeyPattern.source})'`));
assert.match(appLoader, new RegExp(activeKey));
assert.match(appLoader, /import\(MANAGED_STAGE_JSON_UI_MODULE_URL\)[\s\S]*import\(MANAGED_STAGE_JSON_SAMPLE_MODULE_URL\)[\s\S]*loadManagedStageDecorators/);

assert.match(controller, /const VERSION = 'input-persistent-root-card-20260626'/);
assert.match(controller, /POST_BOOTSTRAP_REASSERT_EVENTS/);
assert.match(controller, /viewer:static-shell-bundle-loaded/);
assert.match(controller, /viewer:svg-icons-refreshed/);
assert.match(controller, /viewer:managed-stage-json-ui-ready/);
assert.match(controller, /viewer:app-module-loaded/);
assert.match(controller, /3dmarkup:input-controls-reasserted/);
assert.match(controller, /No file chosen/);
assert.match(controller, /Choose stagedJson/);
assert.match(controller, /Import stagedJson/);
assert.match(controller, /Load BM_CII stagedJson/);
assert.match(controller, /Clear All|clearBtn/);
assert.match(controller, /ensureInputSection\(drawer\)/);
assert.match(controller, /ensureFileDrop\(section\)/);
assert.match(controller, /ensurePrimaryActions\(section\)/);
assert.match(controller, /ensureButton\(actions, 'loadUnifiedModelFileBtn'/);
assert.match(controller, /ensureButton\(actions, 'loadSampleBtn'/);
assert.match(controller, /ensureButton\(actions, 'clearBtn'/);
assert.match(controller, /normalizeWorkflowCopy\(\)/);
assert.match(controller, /sampleStateSeparateFromFileStatus: true/);
assert.match(controller, /inputRootPersistent: section\?\.dataset\.inputRoot === 'persistent'/);
assert.match(controller, /inputIsNotWorkflowCard:/);
assert.match(controller, /forceInputControlsExpanded\(section\)/);
assert.match(controller, /INPUT_CONTENT_SELECTORS/);
assert.match(controller, /document\.getElementById\('inputStatus'\) \|\| document\.getElementById\('inputFileStatus'\)/);
assert.match(controller, /compactStaticInputBlock: Boolean/);
assert.match(controller, /layoutOwner: section\?\.dataset\.layoutOwner \|\| 'source-html-static-css-persistent-root'/);
assert.match(controller, /noRuntimeLayoutStyleInjection: true/);
assert.match(controller, /document\.body\.classList\.add\('input-open'\)/);
assert.match(controller, /__3D_MARKUP_INPUT_ALWAYS_VISIBLE__/);
assert.match(controller, /noPolling: true/);
assert.match(controller, /noMutationObserver: true/);
assert.match(controller, /noSceneTraversal: true/);
assert.doesNotMatch(controller, /new\s+MutationObserver|setInterval\(/);
assert.doesNotMatch(controller, /appendChild\(style\)|createElement\('style'\)|createElement\("style"\)/);
assert.doesNotMatch(controller, /position:\s*sticky\s*!important|\.traverse\(|Choose InputXML|Load InputXML|from InputXML/);

assert.doesNotMatch(managedJsonUi, /^import \* as THREE/m);
assert.doesNotMatch(managedJsonUi, /^import \{ convertManagedStageJsonToRvmAtt \}/m);
assert.match(managedJsonUi, /getManagedStageRuntimeModules\(\)/);
assert.match(perfCss, /input-root-card\[data-section="input"\][\s\S]*min-height:\s*168px/);
assert.match(perfCss, /input-root-card\[data-section="input"\][\s\S]*max-height:\s*none\s*!important/);
assert.match(perfCss, /INPUT is not a collapsible workflow-card/);
assert.match(perfCss, /#loadUnifiedModelFileBtn/);
assert.match(perfCss, /flex-wrap:\s*nowrap/);
assert.match(perfCss, /#inputFileStatus\.input-file-status/);
assert.match(perfCss, /conversion-options-compat-root[\s\S]*display:\s*none\s*!important/);
assert.match(perfCss, /support-workflow-card \.conversion-collapsible-content[\s\S]*display:\s*revert\s*!important/);
assert.match(checklist, /\| ✅ \| C1 — Input controls must always remain visible \|/);
assert.match(checklist, /\| ✅ \| C2 — Required visible input block \|/);
assert.match(checklist, /\| ✅ \| C3 — Real browse\/sample controls hidden \|/);
assert.match(checklist, /\| ✅ \| C4 — Compact static input panel cleanup \|/);
assert.match(pkg.scripts.test, /input-always-visible-phase2\.test\.mjs/);

console.log('input always-visible Phase 2 / persistent root-card gate passed');
