import assert from 'node:assert/strict';
import fs from 'node:fs';

const loader = fs.readFileSync('src/app-loader.js', 'utf8');
const controller = fs.readFileSync('src/managed-stage-json-ui-controller.js', 'utf8');
const sampleController = fs.readFileSync('src/managed-stage-bm-cii-json-sample-controller.js', 'utf8');
const viewerApiBridge = fs.readFileSync('src/managed-stage-viewer-api-bridge.js', 'utf8');
const sampleData = fs.readFileSync('src/managed-stage-bm-cii-json-sample-data.js', 'utf8');
const rawPreview = fs.readFileSync('src/managed-stage-preview-scene.js', 'utf8');
const supportVisualResolver = fs.readFileSync('src/managed-stage-support-visual-resolver.js', 'utf8');

assert.match(loader, /MANAGED_STAGE_JSON_UI_MODULE_URL/);
assert.match(loader, /MANAGED_STAGE_JSON_SAMPLE_MODULE_URL/);
assert.match(loader, /loadManagedStageJsonUiController/);
assert.match(loader, /managed-stage-json-ui-controller\.js/);
assert.match(loader, /managed-stage-bm-cii-json-sample-controller\.js/);

assert.match(controller, /ManagedStageJsonUiController\.v2/);
assert.match(controller, /loadUnifiedModelFileBtn/);
assert.match(controller, /ensureUnifiedModelFileInput/);
assert.match(controller, /xmlFile/);
assert.match(controller, /\.json,\.jscon,application\/json/);
assert.match(controller, /Choose stagedJson/);
assert.match(controller, /Load stagedJson/);
assert.doesNotMatch(controller, /Choose InputXML|Load InputXML|from InputXML|InputXML \/ Managed JSON|Load XML \/ JSON/);
assert.match(controller, /BM_CII_INPUT_managed_stage\.json/);
assert.match(controller, /onUnifiedModelFileChange/);
assert.match(controller, /stopImmediatePropagation/);
assert.match(controller, /looksLikeManagedStageJson/);
assert.match(controller, /inputxml-managed-stage\/v1/);
assert.match(controller, /AVEVA_JSON_FOR_3D_RVM_VIEWER/);
assert.match(controller, /convertManagedStageJsonToRvmAtt/);
assert.match(controller, /createManagedStagePreviewScene/);
assert.match(controller, /previewPipeline: 'raw-managed-stage-json-coordinate-preserving'/);
assert.match(controller, /previewCoordinateAudit/);
assert.doesNotMatch(controller, /createRvmPreviewScene\(result\.exportModel\)/);
assert.match(controller, /BM_CII_STAGED_JSON_EXPECTATIONS/);
assert.doesNotMatch(controller, /BM_CII_INPUTXML_JSON_EXPECTATIONS/);
assert.match(controller, /supportRecordsEmittedToRvm:\s*12/);
assert.match(controller, /supportRvmPrimitiveCount:\s*42/);
assert.match(controller, /primitiveCodeCounts:\s*\{\s*1:\s*0,\s*4:\s*0,\s*8:\s*157\s*\}/);
assert.match(controller, /code1:\s*0/);
assert.match(controller, /cntbCount:\s*56/);
assert.match(controller, /primCount:\s*157/);
assert.match(controller, /supportMaxGlyphExtentMm:\s*100/);
assert.match(controller, /supportMaxClusterOffsetMm:\s*30/);
assert.match(controller, /supportMaxPrimitiveSpanMm:\s*60/);
assert.match(controller, /supportMaxBarRadiusMm:\s*3/);
assert.match(controller, /NON_BLOCKING_MANAGED_STAGE_AUDIT_PATTERNS/);
assert.match(controller, /nonBlockingAuditIssuePatterns:\s*NON_BLOCKING_MANAGED_STAGE_AUDIT_PATTERNS/);
assert.match(controller, /showManagedStageAuditWarnings/);
assert.match(controller, /managed-stage-audit-toast/);
assert.doesNotMatch(controller, /BM_CII_EXPECTATIONS/);
assert.doesNotMatch(controller, /primitiveCodeCounts:\s*\{\s*4:\s*7,\s*8:\s*41\s*\}/);
assert.doesNotMatch(controller, /primCount:\s*48/);
assert.doesNotMatch(controller, /primCount:\s*70/);
assert.match(controller, /downloadRvmBtn/);
assert.match(controller, /downloadAttBtn/);
assert.match(controller, /downloadAuditBtn/);
assert.match(controller, /convertBtn/);
assert.match(controller, /viewer:managed-stage-json-loaded/);
assert.match(controller, /Managed-stage preview audit/);
assert.doesNotMatch(controller, /managedStageJsonFile/);

assert.match(sampleController, /ManagedStageBmCiiJsonSampleController\.v2/);
assert.match(sampleController, /import '\.\/managed-stage-viewer-api-bridge\.js';/);
assert.match(sampleController, /loadManagedStageJsonSampleBtn|loadSampleBtn/);
assert.match(sampleController, /Load BM_CII stagedJson/);
assert.match(sampleController, /stopImmediatePropagation/);
assert.match(sampleController, /createBmCiiManagedStageSampleJson/);
assert.match(sampleController, /managedStageApi\.loadText\(sourceText, SAMPLE_SOURCE_NAME\)/);
assert.doesNotMatch(sampleController, /modelFileInput\.click/);
assert.doesNotMatch(sampleController, /fetch\(SAMPLE_URL/);

assert.match(viewerApiBridge, /ManagedStageViewerApiBridge\.v1/);
assert.match(viewerApiBridge, /__THREED_MARKUP_VIEWER__/);
assert.match(viewerApiBridge, /setModelRoot\(modelRoot, meta = \{\}\)/);
assert.match(viewerApiBridge, /clearModelRoot\(meta = \{\}\)/);
assert.match(viewerApiBridge, /fitRuntimeModel\(runtime, modelRoot\)/);

assert.match(sampleData, /BM_CII_INPUT_managed_stage\.json/);
assert.match(sampleData, /inputxml-managed-stage\/v1/);
assert.match(sampleData, /AVEVA_JSON_FOR_3D_RVM_VIEWER/);
assert.match(sampleData, /stats: \{ components: 40, restraints: 48, branches: 1, children: 52 \}/);
assert.match(sampleData, /FLANGE_PAIR/);
assert.match(sampleData, /FLANGED_VALVE/);
assert.match(sampleData, /BEND_RADIUS/);

assert.match(rawPreview, /ManagedStageRawPreview\.v1/);
assert.match(rawPreview, /ManagedStageCoordinateAudit\.v1/);
assert.match(rawPreview, /createManagedStagePreviewScene/);
assert.match(rawPreview, /assertManagedStagePreviewCoordinatePreservation/);
assert.match(rawPreview, /beforePlanning/);
assert.match(rawPreview, /afterPlanning/);
assert.match(rawPreview, /rendered/);
assert.match(rawPreview, /deltaMm/);
assert.match(rawPreview, /previewAdditiveCue/);
assert.match(rawPreview, /branch-fitting/);
assert.match(rawPreview, /bend/);
assert.match(rawPreview, /managedStageVisibleFallback/);
assert.match(rawPreview, /native raw managed-stage preview scene already applied/);
assert.match(rawPreview, /exportedRvmGeometry: false/);
assert.match(rawPreview, /createManagedStageSupportPreviewObject/);
assert.match(rawPreview, /supportVisualPolicy/);
assert.match(rawPreview, /MANAGED_STAGE_SUPPORT_RESTRAINT_PREVIEW/);

assert.match(supportVisualResolver, /ManagedStageSupportVisualResolver\.v5/);
assert.match(supportVisualResolver, /REST = one upward cone below pipe/);
assert.match(supportVisualResolver, /HOLDDOWN = opposed vertical cones/);
assert.match(supportVisualResolver, /GUIDE = lateral cones/);
assert.match(supportVisualResolver, /LINE_STOP\/LIMIT = transformed Canvas axis/);
assert.ok(supportVisualResolver.includes('X/Y/Z/+X/-X/+Y/-Y/+Z/-Z'));
assert.match(supportVisualResolver, /gap is record-scoped|gapRecordScoped/);
assert.match(supportVisualResolver, /ODx2\/3 applies only to final axial/);
assert.match(supportVisualResolver, /clustered support local offset|support-cluster resolver/);
assert.match(supportVisualResolver, /translucent crossed X rods/);
assert.match(supportVisualResolver, /open-ended low-segment cones/);
assert.match(supportVisualResolver, /supportPreviewRaycastDisabled/);
assert.match(supportVisualResolver, /torus geometry is allowed only for the five SPRING_CAN coils/);

await import('./managed-stage-rvm-audit-gate-nonblocking.test.mjs');
await import('./managed-stage-support-visual-resolver.test.mjs');
await import('./managed-stage-support-cluster.test.mjs');
await import('./managed-stage-viewer-api-bridge.test.mjs');
