import assert from 'node:assert/strict';
import { buildBmCiiPhase11aState, assertNoRawRuntimePayload } from '../fixtures/bend-torus-phase11a-pipeline.mjs';

const state = await buildBmCiiPhase11aState();
assert.equal(state.diagnosticPreviewAudit.ok, true);
assert.equal(state.diagnosticPreviewAudit.previewItemCount, 52);
assert.equal(state.diagnosticPreviewAudit.straightPipeByteProvenPreviewCount, 19);
assert.equal(state.diagnosticPreviewAudit.bendTorusByteProvenPreviewCount, 7);
assert.equal(state.diagnosticPreviewAudit.flangePrimitiveResolvedPreviewCount, 8);
assert.equal(state.diagnosticPreviewAudit.flangeByteProvenPreviewCount, 8);
assert.equal(state.diagnosticPreviewAudit.flangeWriterDeferredPreviewCount, 0);
assert.equal(state.diagnosticPreviewAudit.blockedComponentPreviewCount, 6);
assert.equal(state.diagnosticPreviewAudit.blockedFlangePreviewCount, 0);
assert.equal(state.diagnosticPreviewAudit.blockedValvePreviewCount, 6);
assert.equal(state.diagnosticPreviewAudit.blockedBendPreviewCount, 0);
assert.equal(state.diagnosticPreviewAudit.deferredSupportPreviewCount, 12);
assert.equal(state.diagnosticPreviewAudit.geometryPayloadCount, 0);
assert.equal(state.diagnosticPreviewAudit.meshPayloadCount, 0);
assert.equal(state.diagnosticPreviewAudit.threeObjectCount, 0);
assert.equal(state.diagnosticPreviewAudit.objectUrlCount, 0);
assert.equal(state.diagnosticPreviewAudit.downloadSideEffectCount, 0);
assert.equal(state.diagnosticPreviewAudit.binaryPayloadCount, 0);
assert.equal(state.diagnosticPreviewAudit.textPayloadCount, 0);
assert.equal(state.diagnosticPreviewAudit.glbPayloadCount, 0);
assert.equal(state.diagnosticPreviewAudit.cacheKeyMutationCount, 0);
assert.equal(state.diagnosticPanelViewModel.summaryCards.find((entry) => entry.key === 'flangePrimitiveResolvedCount').value, 8);
assert.equal(state.diagnosticPanelViewModel.summaryCards.find((entry) => entry.key === 'flangeByteProvenCount').value, 8);
assert.equal(state.diagnosticPanelViewModel.summaryCards.find((entry) => entry.key === 'flangeWriterDeferredCount').value, 0);
assert.equal(state.diagnosticPanelViewModel.summaryCards.find((entry) => entry.key === 'blockedFlangeCount').value, 0);
assert.equal(state.diagnosticPanelViewModel.summaryCards.find((entry) => entry.key === 'blockedValveCount').value, 6);
assert.equal(state.diagnosticPanelViewModel.artifactCards.find((entry) => entry.key === 'rvmFlangeSubset').status, 'READY');
assert.equal(state.diagnosticPanelViewModel.artifactCards.find((entry) => entry.key === 'rvmFullModel').status, 'NOT READY');
assertNoRawRuntimePayload({ model: state.diagnosticPreviewModel, panel: state.diagnosticPanelViewModel });

console.log('flange diagnostic status test passed');
