import assert from 'node:assert/strict';
import { readFile } from 'node:fs/promises';
import {
  assertTestArtifactAdapterPlanContract,
  validateTestArtifactAdapterPlanContract
} from '../../src/contracts/index.js';
import { assertTestArtifactAdapterAudit } from '../../src/audit/test-artifact-adapter-audit.js';
import {
  adaptAttExportModelToTestArtifact,
  adaptGlbVisualModelToTestArtifact,
  adaptRvmExportModelToTestArtifact,
  buildTestArtifactAdapterAudit,
  buildTestArtifactAdapterPlan
} from '../../src/artifact-adapters/test-artifact-adapter.js';

const exportModels = await readJson('samples/artifact-adapters/minimal-test-artifact-adapter.input.export-models.json');
const writerAdapterPlan = await readJson('samples/artifact-adapters/minimal-test-artifact-adapter.input.writer-adapter-plan.json');
const writerAdapterAudit = await readJson('samples/artifact-adapters/minimal-test-artifact-adapter.input.writer-adapter-audit.json');
const expectedPlan = await readJson('samples/artifact-adapters/minimal-test-artifact-adapter.expected.plan.json');
const expectedAudit = await readJson('samples/artifact-adapters/minimal-test-artifact-adapter.expected.audit.json');
const exportAudit = {
  schema: 'ExportModelCompilationAudit.v1',
  graphId: 'minimal-test-artifact-fixture',
  ok: true,
  hardErrorCount: 0,
  errors: []
};

const rvmArtifact = adaptRvmExportModelToTestArtifact(exportModels.rvmExportModel, exportAudit, writerAdapterPlan, writerAdapterAudit);
assert.equal(rvmArtifact.artifactReady, false, 'RVM artifact not ready while transform is placeholder');
assert.equal(rvmArtifact.artifactGenerated, false, 'RVM artifact not generated by default');
assert.equal(rvmArtifact.artifactBlocked, true, 'RVM artifact blocked');
assert.equal(rvmArtifact.byteLength, 0, 'RVM byte length stays zero');
assert.ok(rvmArtifact.reason.includes('final review transform policy'));

const attArtifact = adaptAttExportModelToTestArtifact(exportModels.attExportModel, exportAudit, writerAdapterPlan, writerAdapterAudit);
assert.equal(attArtifact.artifactReady, false, 'ATT artifact bridge not ready');
assert.equal(attArtifact.artifactGenerated, false, 'ATT text not generated');
assert.equal(attArtifact.artifactBlocked, true, 'ATT artifact blocked');
assert.equal(attArtifact.textLength, 0, 'ATT text length stays zero');
assert.ok(attArtifact.reason.includes('production writer model bridge'));

const glbArtifact = adaptGlbVisualModelToTestArtifact(exportModels.glbVisualModel, exportAudit, writerAdapterPlan, writerAdapterAudit);
assert.equal(glbArtifact.artifactReady, false, 'GLB artifact not ready');
assert.equal(glbArtifact.artifactGenerated, false, 'GLB artifact not generated');
assert.equal(glbArtifact.artifactBlocked, true, 'GLB artifact blocked');
assert.equal(glbArtifact.byteLength, 0, 'GLB byte length stays zero');
assert.ok(glbArtifact.reason.includes('not implemented'));

const plan = buildTestArtifactAdapterPlan(exportModels, exportAudit, writerAdapterPlan, writerAdapterAudit);
assert.deepEqual(plan, expectedPlan, 'test artifact plan matches golden fixture');
assert.equal(assertTestArtifactAdapterPlanContract(plan).ok, true, 'test artifact plan validates');
assert.equal(plan.blockedArtifactItems.find((entry) => entry.sourceItemId === 'VALVE-1').artifactStatus, 'blocked');
assert.equal(plan.deferredArtifactItems.find((entry) => entry.sourceItemId === 'SUPPORT-1').artifactStatus, 'deferred');
assert.equal(plan.sourceTrace.length, 3, 'source trace covers pipe, blocked valve, and deferred support');
assert.equal(plan.sourceTrace.find((entry) => entry.sourceItemId === 'PIPE-1').artifactStatus, 'writerPlanned');
assert.equal(plan.sourceTrace.find((entry) => entry.sourceItemId === 'VALVE-1').artifactStatus, 'blocked');
assert.equal(plan.sourceTrace.find((entry) => entry.sourceItemId === 'SUPPORT-1').artifactStatus, 'deferred');

for (const forbidden of ['objectUrl', 'downloadUrl', 'domNode', 'canvas', 'threeObject', 'threeGeometry', 'meshGeometry', 'runtimeMutation', 'userVisibleDownload', 'productionWrite', 'appStateMutation', 'cacheKeyMutation']) {
  const bad = structuredClone(plan);
  bad.rvmArtifact[forbidden] = forbidden;
  const result = validateTestArtifactAdapterPlanContract(bad);
  assert.equal(result.ok, false, `contract rejects ${forbidden}`);
  assert.ok(result.errors.some((entry) => entry.includes(forbidden)), `error list mentions ${forbidden}`);
}

const audit = buildTestArtifactAdapterAudit(plan, exportModels, writerAdapterPlan, writerAdapterAudit);
assert.deepEqual(audit, expectedAudit, 'test artifact audit matches golden fixture');
assert.equal(assertTestArtifactAdapterAudit(audit, {
  ok: true,
  hardErrorCount: 0,
  rvmArtifactReady: false,
  rvmArtifactGenerated: false,
  rvmArtifactBlocked: true,
  rvmArtifactByteLength: 0,
  attArtifactReady: false,
  attArtifactGenerated: false,
  attArtifactBlocked: true,
  glbArtifactReady: false,
  glbArtifactGenerated: false,
  glbArtifactBlocked: true,
  sourceTraceCount: 3,
  tracedStraightPipeCount: 1,
  tracedBlockedValveCount: 1,
  tracedDeferredSupportCount: 1,
  runtimeTouched: false,
  browserTouched: false,
  canvasTouched: false,
  objectUrlCount: 0,
  downloadSideEffectCount: 0,
  productionPathMutationCount: 0,
  cacheKeyMutationCount: 0
}).ok, true);

const failedWriterAudit = { ...writerAdapterAudit, ok: false, hardErrorCount: 1, errors: ['writer adapter error'] };
const failedPlan = buildTestArtifactAdapterPlan(exportModels, exportAudit, writerAdapterPlan, failedWriterAudit);
const failedAudit = buildTestArtifactAdapterAudit(failedPlan, exportModels, writerAdapterPlan, failedWriterAudit);
assert.equal(failedAudit.ok, false, 'failed writer audit fails test artifact audit');
assert.ok(failedAudit.errors.some((entry) => entry.includes('WriterAdapterAudit.ok')));

for (const sourcePath of [
  'src/artifact-adapters/test-artifact-adapter.js',
  'src/artifact-adapters/rvm-test-artifact-adapter.js',
  'src/artifact-adapters/att-test-artifact-adapter.js',
  'src/artifact-adapters/glb-test-artifact-adapter.js'
]) {
  const source = await readFile(sourcePath, 'utf8');
  for (const forbidden of ['app.js', 'safe-ui-loader', 'app-loader', 'managed-stage-json-ui-controller', 'managed-stage-rvm-converter', 'canvas', "from 'three'", 'from "three"', 'window.', 'document.', 'rvm-writer', 'att-writer']) {
    assert.equal(source.includes(forbidden), false, `${sourcePath} must not reference ${forbidden}`);
  }
}

console.log('test artifact adapter unit tests passed');

async function readJson(path) {
  return JSON.parse(await readFile(path, 'utf8'));
}
